### ISSUE TITLE
Found 0 unique paths in backup sources on Windows

### ISSUE THREAD

**Issue by nagyesta** [nagyesta/file-barj#159]
### Symptoms

Windows backups are not finding any paths in backup sources (probably due to a regression issue of the cross platform restore)

### Tasks

- [x] Issue is investigated
- [x] Root cause found and documented
- [x] Fix implemented
- [x] Tests updated (if necessary)

### Root cause

During the implementation of #94 , the method which is used creating the glob pattern changed implicitly due to the type change from Path to BackupPath. As a result, Windows paths were no longer using Windows separators (as Backup Paths are using UNIX separators everywhere).

### Changes

- Fixed the affected method
- Added an additional verification step to fail the whole backup when no files are found. This should make the already existing Windows tests to fail if the bug would come back.
